### ISSUE TITLE
act03: why can't we assign a float to an int in java?

### ISSUE THREAD

**Issue by mhciael** [ChrisMayfield/cspogil#10]
here the suggestions don't hold: https://github.com/ChrisMayfield/cspogil/blob/master/CS1/Act03/primitive-types.tex#L130 

ints and float are similarly sized and "compatible" if "numeric to boolean" is the def. probably need to say something about decimal too (I don't know who all is using these activities, but if they're not in a serious relationship with java, a simple reminder here can help explain.

**Comment by ChrisMayfield** [comment]
When I compile this code, I get "Error: incompatible types: possible lossy conversion from float to int". The part in the solution about "numeric to boolean" was only one example (e.g.).

    public class Float2Int {
        public static void main(String[] args) {
            int i = 1;
            float f = 2.3F;
            i = f;  // 
        }
    }
