### ISSUE TITLE
float extremes

### ISSUE THREAD

**Issue by mhciael** [ChrisMayfield/cspogil#11]
https://www.dropbox.com/s/wdn5yw5pl8kgzm3/Screenshot%202017-09-10%2013.26.55.png?dl=0

seems like my jvm or drjava or somewhere in the toolchain disagrees with [the chart in model 2](https://github.com/ChrisMayfield/cspogil/blob/master/CS1/Act03/primitive-types.tex#L17) as far as float's min value (or maybe `Float.MIN_VALUE` is not a good way to determine this?)

**Comment by ChrisMayfield** [comment]
My mistake -- MIN and MAX values are not symmetric like I thought. (Thanks Jingwei.)

> System.out.println(Float.MIN_VALUE);
1.4E-45
> System.out.println(Double.MIN_VALUE);
4.9E-324

**Comment by ChrisMayfield** [comment]
OK, so all three of us misunderstood. For float and double, MIN_VALUE is about precision, not absolute value (the Javadoc says "smallest positive nonzero value").

> (float) -3.4E38
-3.4E38
> (float) -3.4E39
-Infinity

However, the table in Model 2 has a typo: it shouldn't use plus/minus. I'll fix that in the next commit.
