### ISSUE TITLE
Act04 slight over-simplification

### ISSUE THREAD

**Issue by mhciael** [ChrisMayfield/cspogil#12]
looks like https://github.com/ChrisMayfield/cspogil/blob/master/CS1/Act04/conditional.tex#L5 is a slight oversimplification ( i.e. http://introcs.cs.princeton.edu/java/11precedence/ ) (especially in light of https://github.com/ChrisMayfield/cspogil/blob/master/CS1/Act04/conditional.tex#L106 )

**Comment by ChrisMayfield** [comment]
Now that I've swapped Act04 and Act05, the links are:
https://github.com/ChrisMayfield/cspogil/blob/master/CS1/Act05/conditional.tex#L5
https://github.com/ChrisMayfield/cspogil/blob/master/CS1/Act05/conditional.tex#L106
