### ISSUE TITLE
Should we maybe

### ISSUE THREAD

**Issue by hcientist** [ChrisMayfield/cspogil#13]
https://github.com/ChrisMayfield/cspogil/blob/508d6fd19bf64abd9fcb7b74e65a8cf02a022c76/CS1/Act06/for-loops.tex#L89

would it perhaps be useful to break the factorial question into 2 parts? maybe a preceding question that asks them to first write a loop to calculate the factorial of some literal (3? 6?), and then have this one where they calc 20 of them?

**Comment by mhciael** [comment]
what an awful title i gave that ,it was an accident, and accidentally from wrong account...
