### ISSUE TITLE
Why include == in string methods on act09?

### ISSUE THREAD

**Issue by mhciael** [ChrisMayfield/cspogil#15]
So they're learning that they should use `.equals` to compare strings, why should the activity have them see https://github.com/ChrisMayfield/cspogil/blob/master/CS1/Act09/string-methods.tex#L94 that the compiler will optimize for the case of same characters?

**Comment by ChrisMayfield** [comment]
My intention with this example was to show why using == is a bad idea. In some cases (like when the compiler optimizes string literals), the == operator may appear to have the correct result.

**Comment by ChrisMayfield** [comment]
You're right...I'm going to simplify this question and focus on what's important.
