### ISSUE TITLE
add a bit more to act 11 model 2?

### ISSUE THREAD

**Issue by mhciael** [ChrisMayfield/cspogil#18]
maybe add to model 2 that the default constructor "initializes the ints to their default value" or maybe add that between Q6 & Q7?
https://github.com/ChrisMayfield/cspogil/blob/23acec9b3fc97d6d60bc41fcdba00d3c88197373/CS1/Act11/common-methods.tex#L42

it seems like it's a required assumption for Q10d https://github.com/ChrisMayfield/cspogil/blob/23acec9b3fc97d6d60bc41fcdba00d3c88197373/CS1/Act11/common-methods.tex#L107 and Q13 https://github.com/ChrisMayfield/cspogil/blob/23acec9b3fc97d6d60bc41fcdba00d3c88197373/CS1/Act11/common-methods.tex#L131

**Comment by ChrisMayfield** [comment]
good idea, thanks
