### ISSUE TITLE
build.py chokes on 4 files

### ISSUE THREAD

**Issue by StoneyJackson** [ChrisMayfield/cspogil#20]
I haven't had a chance to debug this. Just posting what I know so far.

build.py actually chokes on all the following files the following files.

./CS1/cs1book.tex
./CS1/Other/file-search.tex
./CS1/Other/headers.tex
./CS1/Other/memory.tex

I can build the rest by appending something like "_notme" to each of their names.

Also, after building the others, if I remove "_notme" from cs1book.tex_notme, then rerun `./build.py all` cs1book builds fine. This trick doesn't work for the others.

## Platform

OS: MacOS High Sierra Version 10.13.2 (17C205).

$ pdflatex --version
pdfTeX 3.14159265-2.6-1.40.17 (TeX Live 2016)
kpathsea version 6.2.2
Copyright 2016 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.21; using libpng 1.6.21
Compiled with zlib 1.2.8; using zlib 1.2.8
Compiled with xpdf version 3.04

$ python --version
Python 3.6.3

**Comment by ChrisMayfield** [comment]
Thanks for the heads up. As a workaround, you can run "./build.py CS1 Act" to build all CS1 activities.

**Comment by StoneyJackson** [comment]
Awesome! Works great! Thanks!
