### ISSUE TITLE
Feedback on CS1 Act03 Primitives Model

### ISSUE THREAD

**Issue by StoneyJackson** [ChrisMayfield/cspogil#3]
- "0" is not a primitive. Should be removed from table of literals? Also it appears in question 6 in an assignment.
- Many students stumble the letters in literals (L for long, F for float). I think that's because there are no literals in the model. Maybe a column with sample literals for each type in the model? Or maybe a more focused question like, "From java's perspective, what's the difference between 4 and 4L? Same question for 3.0 and 3.0F." Heck, then you might ask what's the difference between 0 and '0'?
- Students must guess which assignments are illegal and then try to justify there possibly wrong answer with no reference. Maybe give them some legal and illegal assignments, labeled as such. Then ask students to come up with a reason. Then have them apply their reasoning to determine the legality of other assignments.
- To get at assignments between different types are generally not allowed, we might add an assignment between boolean and int or float to question 6.

**Comment by ChrisMayfield** [comment]
Thanks for the great feedback. I agree with all of these items and will make revisions in the next few days.

**Comment by StoneyJackson** [comment]
If it helps, I put this code below on an overhead and had the students answer question 7 (?, the one about forming the concept of when assignments are legal):

```java
public class A {

  public static void main(String [] args) {
    int int_ = 3;
    long long_ = 3L;
    float float_ = 3.0F;
    double double_ = 3.0;

    int_ = int_;
    int_ = long_;     // illegal
    int_ = float_;    // illegal
    int_ = double_;   // illegal

    long_ = int_;
    long_ = long_;
    long_ = float_;   // illegal
    long_ = double_;  // illegal

    float_ = int_;
    float_ = long_;
    float_ = float_;
    float_ = double_; // illegal

    double_ = int_;
    double_ = long_;
    double_ = float_;
    double_ = double_;
  }

}
```

I tried to rework the activity. But I wasn't happy with anything I came up with. So I logged it in an issue instead :)

**Comment by ChrisMayfield** [comment]
I think I'll replace question 8 with your example program, have students guess which ones are allowed, and then verify the answers via facilitation (have groups compare answers, or reveal the compiler errors on the projector).

**Comment by ChrisMayfield** [comment]
I see your point about guessing while having no reference -- we can swap the order of the questions so that the example program comes first, then the concept invention, and then application with question 6.
